
#
# GET test
#
GET http://localhost:8000/api/test HTTP/1.1
Content-Type: application/json

###
#
# POST test
#
POST http://localhost:8000/api/sendmestuff HTTP/1.1
Content-Type: application/json

{   
    "email": "a227yang@uwaterloo.ca"
}

###

# Run verify email to get the verification code
# Run the register to create an account (using the sent verification code)
# Run login to test logging in (website logs out automatically after x time)

#
# Send an email verification
#   sent - the email was sent to their inbox
#   limit - you have already sent an email verification in the last 2 minutes
#   error - they entered an invalid email, turned off emails, blocked our address, etc
#
POST http://localhost:8000/api/auth/verifyemail HTTP/1.1
content-type: application/json

{   
    "email": "a227yang@uwaterloo.ca"
}

###

#
# Test register
#   exists - an account with that email already exists
#   { email, token } - the account was created successfully!

POST http://localhost:8000/api/auth/register HTTP/1.1
content-type: application/json

{
    "name": "Amber Y",
    "age": "14", 
    "gender": "female",    
    "email": "a227yang@uwaterloo.ca",
    "password": "PassWordPassWord", 
    "code": "53965"
}

###

#
# Test login
#   invalid
#       - email --> well the emails invalid duh
#       - password --> password isnt correct
#
#   { email, token } - log in was successful, they have also been redirected

POST http://localhost:8000/api/auth/login HTTP/1.1
content-type: application/json

{  
    "email": "a227yang@uwaterloo.ca",
    "password": "PassWordPassWord"
}