
# Test login
# invalid
#   - email --> well the emails invalid duh
#   - password --> password isnt correct
POST http://localhost:8000/api/auth/login HTTP/1.1
content-type: application/json

{
    "name": "basi",
    "age": "20",
    "gender": "male",    
    "email": "absh9661@mylaurier.ca",
    "password": "1234nnnnn"
}

###

# Test register
#   exists - an account with that email already exists
POST http://localhost:8000/api/auth/register HTTP/1.1
content-type: application/json

{
    "name": "amber",
    "age": "13", 
    "gender": "female",    
    "email": "ambe2468@uwaterloo.ca",
    "password": "1234amber"
}
