

# Register quick without verifying
POST http://localhost:8000/api/auth/quickregister HTTP/1.1
content-type: application/json

[ 
    { 
        "email": "Amber", "name": "Amber", "age": "18", "gender": "female", "password": "Amber",
        "passions": ["Baking", "Hiking", "Weight Lifting", "Movies", "Guitar", "Art Gallery"],
        "about": [],
        "dms":  ["Basi", "Michelle", "Wesgolf"],
        "likes": [],
        "song": {
            "name": "",
            "artist": "",
            "img": "",
            "url": ""
        }
    },
    { 
        "email": "Basi", "name": "Basi", "age": "18", "gender": "male", "password": "Basi",
        "passions": ["Painting", "Hiking", "Hockey", "Movies", "Piano", "Karaoke"],
        "about": [],
        "dms":  [ "Amber", "Michelle", "Wesgolf"],
        "likes": [],
        "song": {
            "name": "",
            "artist": "",
            "img": "",
            "url": ""
        }
    },  
    { 
        "email": "Michelle", "name": "Michelle", "age": "18", "gender": "female", "password": "Michelle",
        "passions": ["Sculpting", "Rock Climbing", "Basketball", "Horror Movies", "Guitar", "Smoking"],
        "about": [],
        "dms":  ["Amber", "Basi", "Wesgolf"],
        "likes": [],
        "song": {
            "name": "",
            "artist": "",
            "img": "",
            "url": ""
        }
    },
    { 
        "email": "Wesgolf", "name": "Wesgolf", "age": "18", "gender": "male", "password": "Wesgolf",
        "passions": ["Cooking", "Camping", "Boxing", "K-Pop", "Cello", "Art Gallery"],
        "about": [],
        "dms":  ["Amber", "Basi", "Michelle"],
        "likes": [],
        "song": {
            "name": "",
            "artist": "",
            "img": "",
            "url": ""
        }
    }
]

###

# Run verify email to get the verification code
# Run the register to create an account (using the sent verification code)
# Run login to test logging in (website logs out automatically after x time)

#
# Send an email verification
#   sent - the email was sent to their inbox
#   limit - you have already sent an email verification in the last 2 minutes
#   error - they entered an invalid email, turned off emails, blocked our address, etc
#
POST http://localhost:8000/api/auth/verifyemail HTTP/1.1
content-type: application/json

{   
    "email": "absh9661@mylaurier.ca"
}

###

#
# Test register
#   exists - an account with that email already exists
#   { email, token } - the account was created successfully!

POST http://localhost:8000/api/auth/register HTTP/1.1
content-type: application/json

{
    "name": "Amber Y",
    "age": "14", 
    "gender": "female",    
    "email": "a227yang@uwaterloo.ca",
    "password": "PassWordPassWord", 
    "code": "53965"
}

###

#
# Test login
#   invalid
#       - email --> well the emails invalid duh
#       - password --> password isnt correct
#
#   { email, token } - log in was successful, they have also been redirected

POST http://localhost:8080/api/auth/login HTTP/1.1
content-type: application/json

{  
    "email": "a227yang@uwaterloo.ca",
    "password": "PassWordPassWord"
}